spring.application.name=travel-planner

server.port=9090
spring.datasource.url=jdbc:postgresql://localhost:5432/travel_planner_db
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


rest.countries.api.url=https://restcountries.com/v3.1/all?fields=name,capital,region,population,currencies,flags

# Security
jwt.secret=3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a756b5c3d4e5f6
